pub const MEM_SIZE = 4096;
pub const PROGRAM_START: u16 = 0x200;
pub const FONTSET_START: u16 = 0x50;
pub const FONTSET_SIZE = 80;
pub const VIDEO_WIDTH = 64;
pub const VIDEO_HEIGHT = 32;
pub const DISPLAY_MEM_SIZE = VIDEO_WIDTH * VIDEO_HEIGHT;
pub const SPRITE_WIDTH = 8;
pub const KEY_COUNT = 16;
